
services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    ports:
      - "3306:3306" # Expose MariaDB port to host
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - ROOT_PASSWORD=${ROOT_PASSWORD}
    volumes:
      - ./requirements/mariadb:/docker-entrypoint-initdb.d
    tty: true
  # nginx:
  #   build: requirements/nginx
  #   container_name: nginx
  #   ports:
  #     - "8080:80" # Host port 80 → Container port 80
  

