networks:
  inception:
    name: inception

services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    # ports:
      # - "3306:3306" # Expose MariaDB port to host (3306 is the default port used by MariaDB and MySQL database servers.)
    env_file: ".env"
    volumes:
      - ./requirements/mariadb:/docker-entrypoint-initdb.d
    networks: [inception]
    tty: true
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    env_file: ".env"
    networks: [inception]
    depends_on: 
      mariadb:
        condition: service_healthy
    restart: always
  nginx:
    build: requirements/nginx
    container_name: nginx
    networks: [inception]
    depends_on: 
      - wordpress
    ports:
      - "443:443" # Only expose HTTPS


