networks:
  inception:
    name: inception

services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    env_file: ".env"
    volumes:
      - mariadb:/var/lib/mysql
    networks: [ inception ]
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 5
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    env_file: ".env"
    networks: [ inception ]
    volumes:
      - wordpress:/var/www/html
    restart: always

    healthcheck:
      test: ["CMD-SHELL", "service php7.4-fpm status | grep running"]
      interval: 10s
      timeout: 5s
      retries: 5

    depends_on:
      mariadb:
        condition: service_healthy
  nginx:
    build: requirements/nginx
    container_name: nginx
    networks: [ inception ]
    env_file: ".env"
    ports:
      - "443:443" # Only expose HTTPS
    volumes:
      - wordpress:/var/www/html
    depends_on:
      wordpress:
        condition: service_healthy

volumes:
  mariadb:
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
  wordpress:
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
      
    